export const ServiceList = [
  {
    id: 1,
    name: 'Jhon Doe',
    service: 'House Cleaning',
    price: '$ 200',
    rating: '4.8',
    reviews: '8,289',
    image: 'https://picsum.photos/400/400?random=1',
    category: 'cleaning',
    isRecommended: true,
    isBookmark: false,
  },
  {
    id: 2,
    name: 'Alice Smith',
    service: 'Kitchen Deep Cleaning',
    price: '$ 150',
    rating: '4.5',
    reviews: '6,512',
    image: 'https://picsum.photos/400/400?random=2',
    category: 'cleaning',
    isRecommended: true,
    isBookmark: false,
  },
  {
    id: 3,
    name: 'Bob Johnson',
    service: 'Wall Painting',
    price: '$ 300',
    rating: '4.9',
    reviews: '12,345',
    image: 'https://picsum.photos/400/400?random=3',
    category: 'painting',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 4,
    name: 'Mark Spacer',
    service: 'Haircut & Beard Trim',
    price: '$ 39',
    rating: '4.8',
    reviews: '10,786',
    image: 'https://picsum.photos/400/400?random=4',
    category: 'barber',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 5,
    name: 'Emily White',
    service: 'Dry Cleaning Service',
    price: '$ 50',
    rating: '4.7',
    reviews: '9,213',
    image: 'https://picsum.photos/400/400?random=6',
    category: 'cleaning',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 6,
    name: 'David Green',
    service: 'Pipe Repair',
    price: '$ 180',
    rating: '4.6',
    reviews: '7,432',
    image: 'https://picsum.photos/400/400?random=6',
    category: 'plumbing',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 7,
    name: 'Sarah Brown',
    service: 'Local Moving',
    price: '$ 250',
    rating: '4.9',
    reviews: '11,124',
    image: 'https://picsum.photos/400/400?random=7',
    category: 'movers',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 8,
    name: 'Michael Adams',
    service: 'Window Cleaning',
    price: '$ 220',
    rating: '4.7',
    reviews: '8,912',
    image: 'https://picsum.photos/400/400?random=8',
    category: 'cleaning',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 9,
    name: 'Jennifer Lee',
    service: 'Refrigerator Repair',
    price: '$ 160',
    rating: '4.4',
    reviews: '5,786',
    image: 'https://picsum.photos/400/400?random=9',
    category: 'repairing',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 10,
    name: 'Chris Taylor',
    service: 'Exterior Wall Painting',
    price: '$ 320',
    rating: '4.9',
    reviews: '13,456',
    image: 'https://picsum.photos/400/400?random=10',
    category: 'painting',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 11,
    name: 'Jessica Parker',
    service: 'Facial and Shave',
    price: '$ 45',
    rating: '4.7',
    reviews: '9,876',
    image: 'https://picsum.photos/400/400?random=11',
    category: 'barber',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 12,
    name: 'Daniel Wilson',
    service: 'Carpet Cleaning',
    price: '$ 55',
    rating: '4.6',
    reviews: '8,321',
    image: 'https://picsum.photos/400/400?random=12',
    category: 'cleaning',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 13,
    name: 'Olivia Miller',
    service: 'Leak Detection Service',
    price: '$ 200',
    rating: '4.8',
    reviews: '10,321',
    image: 'https://picsum.photos/400/400?random=13',
    category: 'plumbing',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 14,
    name: 'Ethan Clark',
    service: 'Furniture Painting',
    price: '$ 280',
    rating: '4.9',
    reviews: '12,543',
    image: 'https://picsum.photos/400/400?random=14',
    category: 'painting',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 15,
    name: 'Sophia Stewart',
    service: 'Rug Cleaning',
    price: '$ 230',
    rating: '4.8',
    reviews: '9,543',
    image: 'https://picsum.photos/400/400?random=15',
    category: 'cleaning',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 16,
    name: 'William Walker',
    service: 'AC Installation',
    price: '$ 140',
    rating: '4.3',
    reviews: '6,243',
    image: 'https://picsum.photos/400/400?random=16',
    category: 'repairing',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 17,
    name: 'Ava Evans',
    service: 'Ceiling Painting',
    price: '$ 340',
    rating: '4.9',
    reviews: '14,567',
    image: 'https://picsum.photos/400/400?random=17',
    category: 'painting',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 18,
    name: 'James Allen',
    service: 'Hot Towel Shave',
    price: '$ 42',
    rating: '4.6',
    reviews: '8,765',
    image: 'https://picsum.photos/400/400?random=18',
    category: 'barber',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 19,
    name: 'Mia Garcia',
    service: 'Bed Linen Cleaning',
    price: '$ 60',
    rating: '4.5',
    reviews: '7,432',
    image: 'https://picsum.photos/400/400?random=19',
    category: 'cleaning',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 20,
    name: 'Noah Perez',
    service: 'Toilet Repair',
    price: '$ 220',
    rating: '4.7',
    reviews: '11,234',
    image: 'https://picsum.photos/400/400?random=20',
    category: 'repairing',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 21,
    name: 'Liam Hall',
    service: 'Laundry Service',
    price: '$ 65',
    rating: '4.4',
    reviews: '8,765',
    image: 'https://picsum.photos/400/400?random=21',
    category: 'laundry',
    isRecommended: false,
    isBookmark: false,
  },
  {
    id: 22,
    name: 'Logan Lopez',
    service: 'Appliance Repair',
    price: '$ 180',
    rating: '4.1',
    reviews: '4,543',
    image: 'https://picsum.photos/400/400?random=22',
    category: 'repairing',
    isRecommended: false,
    isBookmark: false,
  },
];
